name: Remote Build on Jan VM
on:
  push:
    branches: [ main ]
    paths:
      - 'guestbook/**'

jobs:
  build-and-push:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Local Build Script
        run: |
          chmod +x ./build.sh
          ./build.sh
